// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-01-04 15:36:02.805728 -0500 EST m=+0.008515696
package cmd

const GITVERSION = `836db83 Added main.go`
const SEMVER = "0.0.0a"
const GLIDEDEPS = `hash: b7bb2d6509eaa31d68c940e716709f53e9dd3f7de148fac01f61fd29318aed55
updated: 2019-01-03T18:14:18.241903-05:00
imports:
- name: github.com/go-pg/pg
  version: ed4129bb585d65dd6687e49c15c2b3fd12d5cfec
  subpackages:
  - github.com/jinzhu/inflection
- name: github.com/spf13/cobra
  version: ef82de70bb3f60c65fb8eebacbb2d122ef517385
  subpackages:
  - cobra
- name: gitlab.com/elixxir/comms
  version: d26e7e1523cb52ab3ffa67b9088098febd215ded
  repo: git@gitlab.com:elixxir/comms
  vcs: git
testImports: []
`
