// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-03-10 10:12:36.159679 -0800 PST m=+0.033523506
package cmd

const GITVERSION = `93d59af update deps`
const SEMVER = "2.0.0"
const DEPENDENCIES = `module gitlab.com/elixxir/registration

go 1.13

require (
	github.com/denisenkom/go-mssqldb v0.0.0-20200428022330-06a60b6afbbc // indirect
	github.com/fsnotify/fsnotify v1.4.9
	github.com/go-sql-driver/mysql v1.5.0 // indirect
	github.com/golang-collections/collections v0.0.0-20130729185459-604e922904d3
	github.com/jinzhu/gorm v1.9.12
	github.com/jinzhu/now v1.1.1 // indirect
	github.com/lib/pq v1.5.2 // indirect
	github.com/mattn/go-sqlite3 v2.0.3+incompatible // indirect
	github.com/mitchellh/go-homedir v1.1.0
	github.com/pkg/errors v0.9.1
	github.com/smartystreets/assertions v1.1.0 // indirect
	github.com/spf13/cobra v1.1.1
	github.com/spf13/jwalterweatherman v1.1.0
	github.com/spf13/viper v1.7.1
	gitlab.com/elixxir/client v1.2.1-0.20210222224029-4300043d7ce8
	gitlab.com/elixxir/comms v0.0.4-0.20210309193245-64181ff10b68
	gitlab.com/elixxir/crypto v0.0.7-0.20210309193114-8a6225c667e2
	gitlab.com/elixxir/primitives v0.0.3-0.20210309193003-ef42ebb4800b
	gitlab.com/xx_network/comms v0.0.4-0.20210309192940-6b7fb39b4d01
	gitlab.com/xx_network/crypto v0.0.5-0.20210309192854-cf32117afb96
	gitlab.com/xx_network/primitives v0.0.4-0.20210309173740-eb8cd411334a
)

replace google.golang.org/grpc => github.com/grpc/grpc-go v1.27.1
`
